{{- if .Values.traefik.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "web-statistics.fullname" . }}
  labels:
    {{- include "web-statistics.labels" . | nindent 4 }}
  {{- with .Values.traefik.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- toYaml .Values.traefik.ingressRoute.entryPoints | nindent 4 }}
  routes:
    {{- range .Values.traefik.ingressRoute.routes }}
    - match: {{ .match | quote }}
      kind: {{ .kind }}
      services:
        - name: {{ include "web-statistics.fullname" $ }}-{{ .service }}
          port: {{ if eq .service "backend" }}{{ $.Values.backend.service.port }}{{ else }}{{ $.Values.frontend.service.port }}{{ end }}
      {{- with .middlewares }}
      middlewares:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- with .Values.traefik.ingressRoute.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
